### PR TITLE
fix(refs): fixed issue with referencing element of unmounted component

### LINKED ISSUE #199: DOM element provided is null or undefined
Hi, I am still getting this error in some circumstances.

react-plotly.js@2.4.0
plotly.js@1.54.6

I reported this error in the closed issue https://github.com/plotly/react-plotly.js/issues/52 two months ago. But I did not get any reaction, so I am opening a new issue.

I tried to debug my situation and come to finding that library is not checking if a component is mounted in promise handlers in `updatePlotly` function.

**Short story**
Hence, whenever the component mounts and in next moment it unmounts (before all promises in `updatePlotly` resolves), the `syncWindowResize` will call `Plotly.Plots.resize` with `null` (`this.el`) as an argument.

What happened in my situation in details (I've put some checkpoints in comments in bellow snippet):
```js
updatePlotly(shouldInvokeResizeHandler, figureCallbackFunction, shouldAttachUpdateEvents) {
// updatePlotly: checkpoint 1
      this.p = this.p
        .then(() => {
          if (!this.el) {
            let error;
            if (this.unmounting) {
              error = new Error('Component is unmounting');
              error.reason = 'unmounting';
            } else {
              error = new Error('Missing element reference');
            }
            throw error;
          }
// updatePlotly: checkpoint 2
          return Plotly.react(this.el, {
            data: this.props.data,
            layout: this.props.layout,
            config: this.props.config,
            frames: this.props.frames,
          });
        })
        .then(() => this.syncWindowResize(shouldInvokeResizeHandler)  // updatePlotly: checkpoint 3)
        .then(this.syncEventHandlers)
        .then(() => this.figureCallback(figureCallbackFunction))
        .then(shouldAttachUpdateEvents ? this.attachUpdateEvents : () => {})
        .catch(err => {
          if (err.reason === 'unmounting') {
            return;
          }
          console.error('Error while plotting:', err); // eslint-disable-line no-console
          if (this.props.onError) {
            this.props.onError(err);
          }
        });
```

1. `getRef` sets ref correctly
2. `componentDidMount`
3. `updatePlotly` - updatePlotly: checkpoint 1
4. `updatePlotly` - updatePlotly: checkpoint 2
5. `componentWillUnmount`
6. `getRef` unmounting sets ref to `null` (see https://reactjs.org/docs/refs-and-the-dom.html#callback-refs)
7. `updatePlotly` - updatePlotly: checkpoint 3
8. `syncWindowResize` calls Plotly.Plots.resize with argument `this.el`, which was set to `null` (step 6) and that results in `Error while plotting: Error: DOM element provided is null or undefined`.

**Possible solution**
Do not call things in promise `then` handler when unmounting:
```js
// ...
 .then(() => {
  if(!this.unmounting) {
    return this.syncWindowResize(shouldInvokeResizeHandler))
  }
}
// ...
```

**Alternative solution**
Do not use `this.unmountig` at all and implement solution with cancelable promises:
https://reactjs.org/blog/2015/12/16/ismounted-antipattern.html

### PR DESCRIPTION
**Pull request by lavor**
Fixes #199

### CODE REVIEW

**Comment by alexcjohnson** [comment]
Thanks @lavor - this looks good to me but I'd like to get either @dmt0 or @VeraZab to approve it before we merge & publish. I think they're both on holiday this week but I'll make sure we get to it when one of them gets back.

**Comment by lavor** [comment]
Thanks, I will wait for it.

**Review by dmt0 — APPROVED** [review]
Looks good, thanks @lavor!
Also I tested it with react-chart-editor - no issues.

**Comment by lavor** [comment]
Thanks, @dmt0 .
Could you release a new version with thius chcange included, please?

**Comment by dmt0** [comment]
@lavor of course!

**Pull request merged**
