### PR TITLE
add className prop, deprecate fit prop

### PR DESCRIPTION
**Pull request by nicolaskruchten**
fix for #30 and #22

### CODE REVIEW

**Comment by bpostlethwaite** [comment]
What is the alternative to `fit` - removing width and height and setting autosize: true`? Should we document this?

**Comment by nicolaskruchten** [comment]
updated readme.

**Comment by bpostlethwaite** [comment]
Should we document the case where a user can "fit once" by doing all said steps you added minus the `useRelayoutHandler`?

Not blocking though :dancer:

**Comment by nicolaskruchten** [comment]
Well, that's basically just "knowing how plotly.js works" :)

**Pull request merged**
